import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:pietrario_sample_app/screens/splash.dart';
import 'file:///C:/Users/cesar/Desktop/Programming/University/Software/PietrarioApp/lib/screens/timer.dart';

/// DO NOT EDIT THIS FILE
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom]);
  runApp(MaterialApp(
    routes: {
      '/cron': (context) => Timer()
    },
    debugShowCheckedModeBanner: false,
    home: Splash(),
  ));
}